[global]
log.screen = false
log.access_file = ""
log.error_file = ""

[Ferry]
base_url = "https://ferry.fnal.gov:8445/"

[Auth]
default_cert_path = "/tmp/x509up_u{UID}"
default_capath = "/etc/grid-security/certificates"
