name: Ferry CLI tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:


jobs:
  pre_commit:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: setup Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9
    - name: Upgrade pip and install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install pre-commit
        python3 -m pip install pytest
        pre-commit install
    - name: Run pre-commit
      run: pre-commit run --all-files
  test_editable_install:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: setup Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9
    - name: Upgrade pip
      run: python3 -m pip install --upgrade pip
    - name: Install pytest
      run: python3 -m pip install pytest
    - name: Editable install
      run: python3 -m pip install -e .
    - name: Run unit tests only
      run: |
        pytest -m unit
    # upon some condition we can run unit and integration tests
