name: Ferry CLI tests

on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: cern/alma9-base

    steps:
    - uses: actions/checkout@v4
    - name: setup Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip3 install --upgrade pip
        pip3 install flake8
        if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi
    - name: lint python with flake8;
      # can adjust flake8 parameters see: https://flake8.pycqa.org/en/latest/user/error-codes.html
      run: |
        flake8 . --count --show-source --statistics
    - name: run unit tests only
      run: |
        pytest
    # upon some condition we can run unit and integration tests  
  
